---
collections:
  - name: kubernetes.core
    version: ">=6.0.0,<7.0.0"
  - name: community.okd
    version: ">=5.0.0,<6.0.0"
  - name: community.general
    version: ">=13.0.0,<14.0.0"
  - name: ansible.windows
    version: ">=3.0.0,<4.0.0"
