- name: Buscar contas em Secrets
  hosts: localhost
  gather_facts: true
  collections:
    - ansible.windows
    - microsoft.ad
    - community.general

  vars:
    applications_prefix: "^aplic-"
    openshift_host: "{{ lookup ('env', 'K8S_AUTH_HOST') }}"

  tasks:
    - name: Buscar secrets
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        validate_certs: false
      register: secret_data
    
    - name: Inicializar lista
      set_fact:
        application_accounts: []
        
    - name: Extrair username e password
      set_fact:
        application_accounts: >-
          {{
            application_accounts +
            [
              {
                'namespace': item.metadata.namespace,
                'secret_name': item.metadata.name,
                'username': item.data.username | b64decode | trim,
                'password': item.data.password | b64decode | trim
              }
            ]
          }}
      loop: "{{ secret_data.resources }}"
      when:
        - item.type is defined
        - item.type == 'Opaque'
        - item.data is defined
        - "'username' in item.data"
        - "'password' in item.data"
        - (item.data.username | b64decode) is match(applications_prefix)
      no_log: true

    - name: Compartilhar lista
      set_fact:
        application_accounts: "{{ application_accounts }}"
      delegate_facts: true
      delegate_to: 10.83.103.61
   
    - name: Obter usuários únicos
      set_fact:
        usuarios_unicos: "{{ application_accounts | map(attribute='username') | unique | list }}"

    - name: inicializar agrupamento
      set_fact:
        usuarios_agrupados: []

    - name: agrupar por usuario
      set_fact:
        usuarios_agrupados: "{{ usuarios_agrupados + [ resultado ] }}"
      vars:
        contas_usuario: >-
          {{
            application_accounts
            | selectattr('username', 'equalto', item)
            | list
          }}
        resultado: 
          username: "{{ item }}"
          password: "{{ contas_usuario[0].password }}"
          references: "{{ contas_usuario }}"
      loop: "{{ usuarios_unicos }}" 
      loop_control:
        label: "{{ item }}"

    - name: Compartilhar usuarios agrupados
      set_fact:
        usuarios_agrupados: "{{ usuarios_agrupados }}"
      delegate_facts: true
      delegate_to: 10.83.103.61

    - name: Setando ambiente 
      set_fact:
        ambiente_ocp: >-
          {{
            'OCPD1' if openshift_host is search('ocpd1')
            else
            'OCPD2' if openshift_host is search('ocpd2')
            else
            'OCPH1' if openshift_host is search('ocph1')
            else
            'OCPH2' if openshift_host is search('ocph2')
          }}
      
- name: Processar contas
  hosts: windows
  gather_facts: false
  collections:
    - ansible.windows
    - microsoft.ad
    - community.general
  tasks:
    - name: Consultar usuários
      ansible.windows.win_powershell:
        script: |
          $null = Enable-WSManCredSSP -Role Server -Force
          $null = Set-Item -path "WSMan:\localhost\Service\Auth\CredSSP" -Value $true
          Import-Module ActiveDirectory

          $senhaexpira = Get-ADUser -Identity "{{ item.username }}" -Server "scl.corp" -Properties PasswordNeverExpires, "msDS-UserPasswordExpiryTimeComputed"
          if ($senhaexpira.PasswordNeverExpires) {
            $diasrestantes = "senha nunca expira"
            $expireDateFormatado = "N/A"
          } else {
            $expiradata = [datetime]::FromFileTime($senhaexpira."msDS-UserPasswordExpiryTimeComputed")
            [int]$diasrestantes = [Math]::Floor(($expiradata - (Get-Date)).TotalDays)
            $expireDateFormatado = $expiradata.ToString("dd-MM-yyyy HH:mm:ss")
          }
          @{
            Username = "{{ item.username }}"
            ExpireDate = $expireDateFormatado
            DaysLeft = $diasrestantes
          } | ConvertTo-Json -Compress
      vars:
        remote_user: "{{ ansible_user }}"
        remote_password: "{{ ansible_password }}"
      loop: "{{ hostvars[inventory_hostname]['usuarios_agrupados'] }}"
      register: dataexpirasenha_ad
      no_log: true

    - name: inicializar lista todos
      set_fact:
        usuarios_todos: []

    - name: filtrar usuarios todos
      set_fact:
        usuarios_todos: "{{ usuarios_todos + [usuario ] }}"
      vars:
        ps_data: "{{ item.output[0] | from_json }}"
        usuario:
          username: "{{ item.item.username }}"
          password: "{{ item.item.password }}"
          references: "{{ item.item.references }}"
          expira_data: "{{ ps_data.ExpireDate }}"
          days_left: "{{ ps_data.DaysLeft }}"
      loop: "{{ dataexpirasenha_ad.results }}"
      register: todos_usuarios
    
    - name: inicializar lista
      set_fact:
        usuarios_vencendo: []

    - name: filtrar usuarios
      set_fact:
        usuarios_vencendo: "{{ usuarios_vencendo + [usuario ] }}"
      vars:
        ps_data: "{{ item.output[0] | from_json }}"
        usuario:
          username: "{{ item.item.username }}"
          password: "{{ item.item.password }}"
          references: "{{ item.item.references }}"
          expira_data: "{{ ps_data.ExpireDate }}"
          days_left: "{{ ps_data.DaysLeft }}"
      loop: "{{ dataexpirasenha_ad.results }}"
      when:
        - ps_data.DaysLeft != 'senha nunca expira'
        - (ps_data.DaysLeft | int) >= 0
        - (ps_data.DaysLeft | int) <= 10
     
    - name: debugando
      debug:
        var: usuarios_vencendo
      when: 
        - usuarios_vencendo is defined

    - name: Gerar senha
      set_fact:
        usuarios_vencendo_com_senha: >-
          {{
            usuarios_vencendo_com_senha | default ([]) +
            [
              item | combine ({
                'new_password':
                lookup(
                  'password',
                  '/dev/null length=20 chars=ascii_letters,digits,punctuation'
                )
              })
            ]
          }}
      loop: "{{ usuarios_vencendo }}"
      when: 
        - usuarios_vencendo is defined

    - name: Alterando senha do proprio usuario
      ansible.windows.win_powershell:
        script: |
          Add-type -AssemblyName System.DirectoryServices.AccountManagement

          $user = "{{ item.username }}"
          $oldPassword = "{{ item.password }}"
          $newPassword = "{{ item.new_password }}"

          $context = 
            New-Object System.DirectoryServices.AccountManagement.PrincipalContext(
              [System.DirectoryServices.AccountManagement.ContextType]::Domain,
              "scl.corp",
              $user,
              $oldPassword
            )
          if (-not $context.ValidateCredentials($user,$oldPassword)) {
            throw "Senha atual invalida"
          }
          $principal =
          [System.DirectoryServices.AccountManagement.UserPrincipal]::FindByIdentity(
            $context,
            $user
          )
          $principal.ChangePassword(
            $oldPassword,
            $newPassword
          )
          $principal.Save()

          @{
            Username=$user
            Changed=$true
          } | ConvertTo-Json -Compress
      loop: "{{ usuarios_vencendo_com_senha }}"
      register: alteracao_senha
      when: 
        - usuarios_vencendo_com_senha is defined

    - name: Atualizando Secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            namespace: "{{ item.1.namespace }}"
            name: "{{ item.1.secret_name }}"
          data:
            username: "{{ item.0.username | b64encode }}"
            password: "{{ item.0.new_password | b64encode }}"
      loop: "{{ usuarios_vencendo_com_senha | subelements('references') }}"
      register: secrets_updates
      delegate_to: localhost
      run_once: false
      when: 
        - usuarios_vencendo_com_senha is defined     

    - name: Inicializar mapa expiracao
      set_fact:
        expiracao_usuarios: {}

    - name: Montar mapa expiracao
      set_fact:
        expiracao_usuarios: >-
          {{
            expiracao_usuarios |
            combine(
              {
                ps_data.Username: {
                  'days_left': ps_data.DaysLeft,
                  'expire_date': ps_data.ExpireDate
                }
              }
            )
          }}
      vars:
        ps_data: "{{ item.output[0] | from_json }}"
      loop: "{{ dataexpirasenha_ad.results }}"
      when:
        - item.output is defined
        - item.output | length > 0
    
    - name: iniciando relatorio total
      set_fact:
        relatorio_todos: []
        
    - name: montando relatorio total
      set_fact:
        relatorio_todos: "{{ relatorio_todos + [ registro ] }}"
      vars:
        registro:
          username: "{{ item.username }}"
          namespace: "{{ item.namespace }}"
          secret_name: "{{ item.secret_name }}"
          days_left: >-
            {{
              expiracao_usuarios[item.username].days_left
              if item.username in expiracao_usuarios
              else 'N/A'
            }}
      loop: "{{ hostvars['10.83.103.61'].application_accounts }}"

    - name: Montar HTML todos
      set_fact:
        html_todosuserpods: |
          <html>
          <body>
            <h5> Abaixo todos os usuários: </h5>
            <table style="border-collapse:collapse;font-family:Calibri,Arial,sans-serif;font-size:11px;width:100%">
              <tr bgcolor="#D9EAD3">
                <th style="background:#8FAADC;border:1px solid #000;">Usuario</th>
                <th style="background:#8FAADC;border:1px solid #000;">Namespace</th>
                <th style="background:#8FAADC;border:1px solid #000;">Secret</th>
                <th style="background:#8FAADC;border:1px solid #000;">Expira em (dias)</th>
              </tr>
              {% for item in relatorio_todos %}
              <tr>
                <td style="background:#00B050;color:white;border:1px solid #000;text-align:center;">{{ item.username }}</td>
                <td style="border:1px solid #000;text-align:center;">{{ item.namespace }}</td>
                <td style="border:1px solid #000;text-align:center;">{{ item.secret_name }}</td>
                <td style="border:1px solid #000;text-align:center;">{{ item.days_left }}</td>
              </tr>
              {% endfor %}
            </table>
            <b> TOTAL DE SECRETS EM {{ ambiente_ocp }}:</b>
            {{ relatorio_todos | length }}
          </body>
          </html>
          
    
    - name: iniciando relatorio
      set_fact:
        relatorio_alteracoes: []
        
    - name: montando relatorio
      set_fact:
        relatorio_alteracoes: "{{ relatorio_alteracoes + [ {
          'username': item.item.0.username,
          'namespace': item.item.1.namespace,
          'secret_name': item.item.1.secret_name
        } ] }}"
      loop: "{{ secrets_updates.results }}"
      when: 
        - usuarios_vencendo_com_senha is defined     

    - name: Montar HTML
      set_fact:
        html_userpods: |
          <html>
          <body>
          {% if usuarios_vencendo_com_senha is not defined or usuarios_vencendo_com_senha | length == 0 %}
            <h5 style="background:green;color:white">
              Olá! Nenhum usuário requer atualização de credencial :)!
            </h5>
          </body>
          </html>
          {% else %}
            <h5>
              Olá! Foram identificados e alterados os usuarios com expiração em até 10 dias
            </h5>
            <table style="border-collapse:collapse;font-family:Calibri,Arial,sans-serif;font-size:11px;width:100%">
              <tr bgcolor="#D9EAD3">
                <th style="background:#8FAADC;border:1px solid #000;">Usuario</th>
                <th style="background:#8FAADC;border:1px solid #000;">Namespace</th>
                <th style="background:#8FAADC;border:1px solid #000;">Secret</th>
              </tr>
              {% for item in relatorio_alteracoes %}
              <tr>
                <td style="background:#00B050;color:white;border:1px solid #000;text-align:center;">{{ item.username }}</td>
                <td style="border:1px solid #000;text-align:center;">{{ item.namespace }}</td>
                <td style="border:1px solid #000;text-align:center;">{{ item.secret_name }}</td>
              </tr>
              {% endfor %}
            </table>
            <br>
            <b> TOTAL DE SECRETS ATUALIZADOS EM {{ ambiente_ocp }}:</b>
              {{ relatorio_alteracoes | length }}
            <br>
          {% endif %}  
          </body>
          </html>
          
    - name: Enviando email do relatorio
      community.general.mail:
        host: mail.energisa.com.br 
        port: 25
        subtype: html
        from: iac-infra@energisa.com.br 
        to:
          - jayder.carneiro@energisaterceiros.com.br
        subject: Relatorio de credenciais {{ ambiente_ocp }} - {{ now(fmt='%d/%m/%Y') }} 
        body: |
          {{ html_todosuserpods }}
          <br>
          {{ html_userpods }}
#          "{{ ansible_user }}"
      delegate_to: localhost
      run_once: true
#      when: relatorio_alteracoes | length > 0        
