- name: Buscar contas em Secrets
  hosts: localhost
  gather_facts: true

  vars:
    applications_prefix: "^aplic-"

  tasks:

    - name: Buscar secrets
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        validate_certs: false
      register: secret_data
    
    - name: Inicializar lista
      set_fact:
        application_accounts: []
        
    - name: Extrair username e password
      set_fact:
        application_accounts: >-
          {{
            application_accounts +
            [
              {
                'namespace': item.metadata.namespace,
                'secret_name': item.metadata.name,
                'username': item.data.username | b64decode | trim,
                'password': item.data.password | b64decode | trim
              }
            ]
          }}
      loop: "{{ secret_data.resources }}"
      when:
        - item.type is defined
        - item.type == 'Opaque'
        - item.data is defined
        - "'username' in item.data"
        - "'password' in item.data"
        - (item.data.username | b64decode) is match(applications_prefix)
      no_log: true

    - name: Compartilhar lista
      set_fact:
        application_accounts: "{{ application_accounts }}"
      delegate_facts: true
      delegate_to: 10.83.103.61
      
- name: Processar contas
  hosts: windows
  gather_facts: false
  collections:
    - ansible.windows
    - microsoft.ad
  
  tasks:
    - name: Consultar usuários
      ansible.windows.win_powershell:
        script: |
          $null = Enable-WSManCredSSP -Role Server -Force
          $null = Set-Item -path "WSMan:\localhost\Service\Auth\CredSSP" -Value $true
          Import-Module ActiveDirectory

          $senhaexpira = Get-ADUser -Identity "{{ item.username }}" -Server "scl.corp" -Properties PasswordNeverExpires, "msDS-UserPasswordExpiryTimeComputed"
          if ($senhaexpira.PasswordNeverExpires) {
            $diasrestantes = "senha nunca expira"
            $expireDateFormatado = "N/A"
          } else {
            $expiradata = [datetime]::FromFileTime($senhaexpira."msDS-UserPasswordExpiryTimeComputed")
            [int]$diasrestantes = [Math]::Floor(($expiradata - (Get-Date)).TotalDays)
            $expireDateFormatado = $expiradata.ToString("dd-MM-yyyy HH:mm:ss")
          }
          @{
            Username = "{{ item.username }}"
            ExpireDate = $expireDateFormatado
            DaysLeft = $diasrestantes
          } | ConvertTo-Json -Compress
      vars:
        remote_user: "{{ ansible_user }}"
        remote_password: "{{ ansible_password }}"
      loop: "{{ application_accounts }}"
      register: dataexpirasenha_ad

    - name: Obter usuários únicos
      set_fact:
        usuarios_unicos: "{{ application_accounts | map(attribute='username') | unique | list }}"

    - name: inicializar agrupamento
      set_fact:
        usuarios_agrupados: []

    - name: agrupar por usuario
      set_fact:
        usuarios_agrupados: "{{ usuarios_agrupados + [ resultado ] }}"
      vars:
        contas_usuario: >-
          {{
            application_accounts
            | selectattr('username', 'equalto', item)
            | list
          }}
          resultado: 
            username: "{{ item }}"
            password: "{{ contas_usuario[0].password }}"
            references: "{{ contas_usuarios }}"
      loop: "{{ usuarios_unicos }}"  

    - name: secrets por usuario
      debug:
        var: usuarios_agrupados
