- name: Deletando pods
  hosts: localhost
  gather_facts: false

  collections: 
    - kubernetes.core
  
  tasks:
    - name: Delete Pod (force)
      kubernetes.core.k8s:
        state: absent
        kind: Pod
        name: "{{ var_namepod }}"
        namespace: "{{ var_namespace }}"
        delete_options:
          gracePeriodSeconds: 0
