- name: IPAM
  hosts: localhost
  gather_facts: false

  collections: 
    - bagre.ipam

  tasks:
    - name: Descobre o próximo IP livre
      bagre.ipam.next_free_ip:
        endpoint: https://energisa-amc.ivanticloud.com
        token: 
        subnet_cidr: 10.83.102.0/24
      register: livre
    
    - name: Mostra o IP
      ansible.builtin.debug:
        msg: "Próximo IP livre: {{ livre.ip.address }}"
