- name: Descobrir hosts na VLAN
  hosts: all
  gather_facts: false

  vars:
    subnet: "10.83.107.0/24"

  tasks:

    - name: Scan VLAN
      shell: |
        nmap -sn "{{ subnet }}" -oG - | awk '/Up$/{print $2}'
      register: hosts_encontrados

    - name: Criar inventário dinâmico
      add_host:
        name: "{{ item }}"
        groups: discovered
        debug: "{{ item }}"
      loop: "{{ hosts_encontrados.stdout_lines }}"
