- hosts: localhost
  gather_facts: false

  tasks:
    - shell: whoami
      register: user

    - shell: which ping
      register: ping

    - shell: which nmap
      register: nmap

    - debug:
        msg:
          - "USER={{ user.stdout }}"
          - "PING={{ ping.stdout }}"
          - "NMAP={{ nmap.stdout }}"
