---
# Dominio AD
ad_domain: "scl.corp"

# Host Windows que possui acesso ao AD
ad_server: "10.83.103.61"

# Regras de rotacao
password_rotation_min_days: 0
password_rotation_max_days: 10
password_min_length: 12
password_max_length: 20
password_special_chars: '!@#%^&*_-+='

# V1: nao reinicia workloads.
restart_deployments: false

# OCP
ocp_validate_certs: true

# Prefixo dos usuarios elegiveis
aplic_user_prefix: "aplic-user-"

# E-mail
mail_host: "smtp.energisa.com.br"
mail_port: 25
mail_from: "iac-infra@energisa.com.br"
mail_to:
  - "jayder.carneiro@energisaterceiros.com.br"
mail_cc: []
mail_subject_prefix: "Atualização de credenciais"
