---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

options:
  package_manager_path: /usr/bin/microdnf

requirements:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend_galaxy:
    - ADD collections/ /tmp/collections/
